
export const CUSTOMER_DB = [
    {
        id: 1,
        imageUrl:'../../assets/img/faces/clem-onojeghuo-3.jpg',
        email: 'asd123@gmail.com',
        userName: 'Umesh',
        password: 'aaaaaa',
        repeatPassword: 'aaaaaa',
        role: 'admin',
        color: ['Green'],
        status: 1,
        country: 'Nepal',
    },
    {
        id: 2,
        imageUrl:'../../assets/img/faces/clem-onojeghuo-2.jpg',
        email: 'asd123@gmail.com',
        userName: 'Ganesh',
        password: 'ganuaa',
        repeatPassword: 'ganuaa',
        role: 'admin',
        color: ['Pink'],
        status: 2,
        country: 'Bangladesh',
    },

    {
        id: 3,
        imageUrl:'../../assets/img/faces/erik-lucatero-2.jpg',
        email: 'asd123@gmail.com',
        userName: 'Binod',
        password: 'japuaa',
        repeatPassword: 'japuaa',
        role: 'admin',
        color: ['White'],
        status: 3,
        country: 'USA',
    },
    {
        id: 4,
        imageUrl:'../../assets/img/faces/clem-onojeghuo-3.jpg',
        email: 'asd123@gmail.com',
        userName: 'Jaydeep',
        password: 'baaaaa',
        repeatPassword: 'baaaaa',
        role: 'manager',
        color: ['Green', 'White'],
        status: 4,
        country: 'Germany',
    },
    {
        id: 5,
        imageUrl:'../../assets/img/faces/joe-gardner-2.jpg',
        email: 'manager@gmail.com',
        userName: 'Hari',
        password: 'manager',
        repeatPassword: 'manager',
        role: 'manager',
        color: ['Green', 'Purple'],
        status: 4,
        country: 'Bhutan',
    },
    {
        id: 6,
        imageUrl:'../../assets/img/faces/kaci-baum-2.jpg',
        email: 'rambo@gmail.com',
        userName: 'Ram',
        password: 'ramboo',
        repeatPassword: 'ramboo',
        role: 'manager',
        color: ['Black', 'red'],
        status: 1,
        country: 'Afghanistan',
    },
    {
        id: 7,
        imageUrl:'../../assets/img/faces/kaci-baum-2.jpg',
        email: 'hamro@gmail.com',
        userName: 'Umesh',
        password: '9843223667',
        repeatPassword: '9843223667',
        role: 'user',
        color: ['red', 'Blue'],
        status: 2,
        country: 'Maldives',
    },
    {
        id: 8,
        imageUrl:'../../assets/img/faces/kaci-baum-2.jpg',
        email: 'ccc@gmail.com',
        userName: 'Umesh',
        password: 'caaaaa',
        repeatPassword: 'caaaaa',
        role: 'user',
        color: ['White', 'Pink'],
        status: 4,
        country: 'China',
    },
    {
        id: 9,
        imageUrl:'../../assets/img/faces/kaci-baum-2.jpg',
        email: 'we@gmail.com',
        userName: 'Umesh',
        password: 'wewewe',
        repeatPassword: 'wewewe',
        role: 'user',
        color: ['Yellow', 'Purple'],
        status: 3,
        country: 'Japan',
    },
    {
        id: 10,
        imageUrl:'../../assets/img/faces/kaci-baum-2.jpg',
        email: 'user@gmail.com',
        userName: 'Umedsh',
        password: 'userer',
        repeatPassword: 'userer',
        role: 'user',
        color: ['Black', 'White'],
        status: 1,
        country: 'North Korea',
    }
];